// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Get Groups
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/magicbutton/magic-zones/execution"
	"github.com/magicbutton/magic-zones/schemas"
	"github.com/magicbutton/magic-zones/utils"
)

func UsecasesGetGroupsPost(ctx context.Context, args []string) (*schemas.AllGroups, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "magic-zones", "05-usecases", "10-get-groups.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("magic-zones"), "all-groups.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.AllGroups{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
